# Written by calib_node auto.
safety_node:
  ros__parameters:
    cmd_linear_sign: 1.0
    stop_distance: 0.018
    clear_distance: 0.028
    us_stop_distance: 0.020
    us_clear_distance: 0.028
    front_half_width_deg: 8.0
    lidar_yaw_offset: 3.31612558
    robot_radius: 0.076
    camera_as_wall: false
    camera_block_as_wall: false
    imu_roll0: 0.0
    imu_pitch0: 0.0
