control_node:
  ros__parameters:
    cmd_vel_topic: /cmd_vel_raw
    odom_topic: /odom
    vmax: 0.014
    vmax_think: 0.003
    vmin: 0.003
    think_dist: 0.04
    wmax: 0.35
    kp: 1.0
    kp_yaw: 1.4
    tolerance: 0.008
    yaw_tolerance_deg: 2.0
    odom_timeout: 0.5
