"""Module harness records: validate progress/logs, generate index and status.

Usage (from the repository root)::

    python tools/harness/rosy_harness.py generate   # rewrite index.md files and STATUS.md
    python tools/harness/rosy_harness.py lint       # errors exit 1; staleness is a warning

Design: ``docs/plans/2026-09-15-module-harness-design.md`` (ADR D-61).
ROS-free: standard library plus PyYAML, so it runs on Windows hosts and in CI.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

import yaml

CONFIG = Path("tools") / "harness" / "harness.yaml"
GATES = ("SOURCE", "LOCAL", "ROS-SIM", "ARTIFACT", "DEVICE", "FIELD")
STATES = ("GO", "HOLD", "PARKED", "N/A")
REQUIRED_PROGRESS = ("module", "owner", "last_verified", "gates")
LOG_FIELDS = ("변경", "증거", "gate 변화")
RECENT_LOGS = 5
UNCOMMITTED = "uncommitted"

ADR_ID = re.compile(r"^D-(\d+)$")
COMMIT = re.compile(rf"^(?:[0-9a-f]{{7,40}}|{UNCOMMITTED})$")
LOGICAL_MODULE = re.compile(r"^M\d{2}$")
LOG_HEADING = re.compile(rf"^## (\d{{4}}-\d{{2}}-\d{{2}}) · ([0-9a-f]{{7,40}}|{UNCOMMITTED}) · (\S.*)$")
FENCE = re.compile(r"^(```|~~~)")
CONFLICT_MARKER = re.compile(r"^(<<<<<<<|=======|>>>>>>>)( |$)")
ADR_INDEX_ROW = re.compile(r"^\| (D-\d+) \| ([^|]+?) \| ([^|]+?) \|\s*$", re.MULTILINE)
# D-36 was recorded as "## D-36: title (date)"; accept that form rather than rewrite the log.
ADR_BODY_HEADING = re.compile(r"^## (D-\d+):? (.+)$", re.MULTILINE)

# The 2026-09-19 domain-regroup session landed four log entries in a
# pre-harness heading shape (`## YYYY-MM-DD: subject`). logs.md is append-only
# and the history gate (is_append_only) makes reformatting committed lines a
# violation, so these exact lines are excused by name — the same pattern as
# secret_scan.py's KNOWN_FIXTURES and the same reasoning as ADR_BODY_HEADING's
# optional colon. New headings must still match LOG_HEADING.
#
# The 2026-09-20 fleet session's D-131 phases 2-3 entry was swept into a
# concurrent commit and is missing the literal `- 변경:` bullet; editing it
# in place would violate the same history gate, so it is excused by exact
# name too. Same class of defect: a committed line that cannot be reformed.
KNOWN_LEGACY_HEADINGS = frozenset({
    "## 2026-09-19: Core 패키지 모듈화 (Level 3 Phase 1)",
    "## 2026-09-19: Core 패키지 모듈화 (Level 3 Phase 2 & 3)",
    "## 2026-09-19: Core 패키지 모듈화 완료 (Level 3 Phase 4 & 5)",
    "## 2026-09-19: Fleet 도메인 폴더명 변경 (site)",
    "## 2026-09-20 · uncommitted · feat(fleet): Robot Selection lands (FOR-001) and the gather bench puts a number on N (D-131 phases 2-3)",
})

GENERATED_MARK = (
    "<!-- GENERATED by tools/harness/rosy_harness.py generate. "
    "Edit progress.md, logs.md, or the ADR log instead. -->"
)


class HarnessError(ValueError):
    """A harness record cannot be read at all."""


def _normalize(text: str) -> str:
    return text.removeprefix("﻿").replace("\r\n", "\n")


def _adr_number(adr_id: str) -> int:
    return int(adr_id.split("-")[1])


# --- frontmatter -----------------------------------------------------------


def split_frontmatter(text: str) -> tuple[dict, str]:
    text = _normalize(text)
    if not text.startswith("---\n"):
        raise HarnessError("missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise HarnessError("unterminated YAML frontmatter")
    meta = yaml.safe_load(text[4:end]) or {}
    if not isinstance(meta, dict):
        raise HarnessError("frontmatter is not a mapping")
    return meta, text[end + len("\n---\n"):].lstrip("\n")


def _optional_frontmatter(path: Path) -> dict:
    try:
        meta, _ = split_frontmatter(path.read_text(encoding="utf-8"))
    except (ValueError, OSError, yaml.YAMLError):
        return {}
    return meta


# --- progress.md -----------------------------------------------------------


def validate_progress(meta: dict, known_adrs: set[str] | None = None) -> list[str]:
    errors = [f"missing field: {key}" for key in REQUIRED_PROGRESS if key not in meta]

    if "last_verified" in meta:
        verified = meta["last_verified"]
        if not isinstance(verified, dict):
            errors.append("last_verified must map commit and date")
        else:
            commit = verified.get("commit")
            if not isinstance(commit, str) or not COMMIT.match(commit):
                errors.append(f"last_verified.commit must be a quoted 7-40 hex commit or {UNCOMMITTED!r}")
            if not isinstance(verified.get("date"), dt.date):
                errors.append("last_verified.date must be YYYY-MM-DD")

    gates = meta.get("gates")
    if "gates" in meta and not isinstance(gates, dict):
        errors.append("gates must be a mapping")
        gates = {}
    gates = gates or {}
    if "gates" in meta:
        errors += [f"missing gate: {g} (write N/A when the profile excludes it)" for g in GATES if g not in gates]
    for name, gate in gates.items():
        if name not in GATES:
            errors.append(f"unknown gate: {name}")
            continue
        if not isinstance(gate, dict):
            errors.append(f"{name}: gate must be a mapping")
            continue
        state = gate.get("state")
        if state not in STATES:
            errors.append(f"{name}: unknown state {state!r}")
        elif state == "GO":
            errors += [f"{name}: GO requires {field}" for field in ("evidence", "cmd") if not gate.get(field)]
        elif state == "HOLD" and not gate.get("blocker"):
            errors.append(f"{name}: HOLD requires blocker")

    for adr_id in meta.get("adrs") or []:
        if not isinstance(adr_id, str) or not ADR_ID.match(adr_id):
            errors.append(f"malformed ADR id: {adr_id}")
        elif known_adrs is not None and adr_id not in known_adrs:
            errors.append(f"unknown ADR: {adr_id}")

    for logical in meta.get("logical_modules") or []:
        if not isinstance(logical, str) or not LOGICAL_MODULE.match(logical):
            errors.append(f"malformed logical module: {logical}")

    return errors


# --- logs.md ---------------------------------------------------------------


@dataclass(frozen=True)
class LogEntry:
    date: str
    commit: str
    summary: str
    body: str

    @property
    def heading(self) -> str:
        return f"## {self.date} · {self.commit} · {self.summary}"


def _scan_log(text: str) -> tuple[list[LogEntry], list[str]]:
    entries: list[LogEntry] = []
    errors: list[str] = []
    current: tuple[str, str, str] | None = None
    body: list[str] = []
    in_fence = False

    def close() -> None:
        if current is not None:
            entries.append(LogEntry(*current, body="\n".join(body)))

    for number, line in enumerate(_normalize(text).split("\n"), start=1):
        if FENCE.match(line):
            in_fence = not in_fence
        if in_fence or FENCE.match(line) or not line.startswith("## "):
            if current is not None:
                body.append(line)
            continue
        close()
        body = []
        match = LOG_HEADING.match(line)
        if match:
            current = match.groups()
        elif line in KNOWN_LEGACY_HEADINGS:
            # A known pre-harness heading: a boundary, not a registered entry.
            current = None
        else:
            current = None
            errors.append(f"line {number}: malformed heading {line!r}")
    close()
    return entries, errors


def parse_log(text: str) -> list[LogEntry]:
    return _scan_log(text)[0]


def validate_log(text: str) -> list[str]:
    entries, errors = _scan_log(text)
    seen: set[str] = set()
    previous: str | None = None
    for entry in entries:
        try:
            dt.date.fromisoformat(entry.date)
        except ValueError:
            errors.append(f"{entry.heading}: invalid date")
        if entry.heading in seen:
            errors.append(f"duplicate entry: {entry.heading}")
        seen.add(entry.heading)
        for name in LOG_FIELDS:
            if entry.heading in KNOWN_LEGACY_HEADINGS:
                # Excused headings are already committed and the history gate
                # forbids reforming them — their field defects are recorded
                # here, not fixable in place.
                continue
            if not re.search(rf"^- {re.escape(name)}:", entry.body, flags=re.MULTILINE):
                errors.append(f"{entry.heading}: missing '- {name}:'")
        if previous is not None and entry.date < previous:
            errors.append(f"{entry.heading}: out of order (after {previous})")
        previous = max(previous or entry.date, entry.date)
    return errors


def is_append_only(old: str, new: str) -> bool:
    old, new = _normalize(old), _normalize(new)
    old = old if old.endswith("\n") else old + "\n"
    new = new if new.endswith("\n") else new + "\n"
    return new.startswith(old)


# --- ADR log ---------------------------------------------------------------


@dataclass(frozen=True)
class AdrLog:
    index: dict[str, tuple[str, str]]
    bodies: dict[str, str]
    duplicates: tuple[str, ...] = ()


def parse_adr_log(text: str) -> AdrLog:
    text = _normalize(text)
    first_body = ADR_BODY_HEADING.search(text)
    index_text = text[: first_body.start()] if first_body else text
    index = {m.group(1): (m.group(2).strip(), m.group(3).strip()) for m in ADR_INDEX_ROW.finditer(index_text)}
    bodies: dict[str, str] = {}
    duplicates: list[str] = []
    for match in ADR_BODY_HEADING.finditer(text):
        if match.group(1) in bodies:
            duplicates.append(match.group(1))
        bodies[match.group(1)] = match.group(2).strip()
    return AdrLog(index=index, bodies=bodies, duplicates=tuple(duplicates))


def validate_adr_log(adr: AdrLog, gaps: dict[str, str]) -> list[str]:
    errors = [f"{adr_id}: duplicate body section" for adr_id in adr.duplicates]
    for adr_id in sorted(set(adr.bodies) - set(adr.index), key=_adr_number):
        errors.append(f"{adr_id}: body section missing from index")
    for adr_id in sorted(set(adr.index) - set(adr.bodies), key=_adr_number):
        errors.append(f"{adr_id}: index row has no body section")

    present = set(adr.index) | set(adr.bodies)
    highest = max((_adr_number(i) for i in present), default=0)
    for number in range(1, highest + 1):
        adr_id = f"D-{number}"
        if adr_id not in present and adr_id not in gaps:
            errors.append(f"{adr_id}: missing and not declared in adr_gaps")
    for adr_id in sorted(gaps, key=_adr_number):
        if adr_id in present:
            errors.append(f"{adr_id}: declared gap now exists; remove it from adr_gaps")
    return errors


# --- rendering -------------------------------------------------------------


def load_config(repo: Path) -> dict:
    return yaml.safe_load((repo / CONFIG).read_text(encoding="utf-8"))


def _link(from_dir: Path, target: Path) -> str:
    return quote(os.path.relpath(target, from_dir).replace(os.sep, "/"), safe="/-._~")


def _title(path: Path) -> str:
    meta = _optional_frontmatter(path)
    if isinstance(meta.get("title"), str):
        return meta["title"]
    for line in _normalize(path.read_text(encoding="utf-8", errors="replace")).split("\n"):
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def _names_module(meta: dict, name: str) -> bool:
    modules = meta.get("modules") or []
    return meta.get("module") == name or (isinstance(modules, list) and name in modules)


def _read_progress(repo: Path, module: dict) -> dict:
    path = repo / module["path"] / "progress.md"
    try:
        meta, _ = split_frontmatter(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise HarnessError(f"{module['name']}: missing progress.md") from exc
    except (yaml.YAMLError, UnicodeDecodeError) as exc:
        raise HarnessError(f"{module['name']}: unreadable progress.md: {exc}") from exc
    return meta


def _read_log(repo: Path, module: dict) -> list[LogEntry]:
    path = repo / module["path"] / "logs.md"
    return parse_log(path.read_text(encoding="utf-8")) if path.is_file() else []


def render_module_index(repo: Path, module: dict, adr: AdrLog, adr_log_path: Path) -> str:
    base = repo / module["path"]
    meta = _read_progress(repo, module)
    name = module["name"]
    # Titles only: an ADR's status changes (Proposed -> Accepted) must not make
    # every module index stale on an unrelated commit. Status lives in the log.
    lines = [
        GENERATED_MARK,
        f"# {name} index",
        "",
        "기록: [progress.md](progress.md) · [logs.md](logs.md) · [AGENTS.md](AGENTS.md)",
        "",
        "## 결정 (ADR)",
        "",
        f"출처와 Status: [ROSY ADR Log]({_link(base, adr_log_path)}). 목록은 `progress.md`의 `adrs`다.",
        "",
        "| ID | 제목 |",
        "|---|---|",
    ]
    for adr_id in sorted(set(meta.get("adrs") or []), key=_adr_number):
        title, _ = adr.index.get(adr_id, ("(ADR log에 없음)", "?"))
        lines.append(f"| {adr_id} | {title} |")

    plans = {repo / p for p in meta.get("plans") or []}
    plans |= {p for p in (repo / "docs" / "plans").glob("*.md") if _names_module(_optional_frontmatter(p), name)}
    lines += ["", "## 계획·결과 문서", ""]
    ordered = sorted(plans, key=lambda p: p.relative_to(repo).as_posix())
    lines += [f"- [{p.name}]({_link(base, p)})" for p in ordered] or ["- 없음"]

    solutions_root = repo / "docs" / "solutions"
    solutions = sorted(
        (p for p in solutions_root.rglob("*.md") if p.name != "AGENTS.md" and _names_module(_optional_frontmatter(p), name)),
        key=lambda p: p.relative_to(solutions_root).as_posix(),
    )
    lines += ["", "## 교훈 (docs/solutions)", ""]
    lines += [f"- [{_title(p)}]({_link(base, p)})" for p in solutions] or ["- 없음"]

    lines += ["", "## 시험", ""]
    lines += [f"- `{t}`" for t in module.get("tests") or []] or ["- 없음"]

    recent = list(reversed(_read_log(repo, module)[-RECENT_LOGS:]))
    lines += ["", "## 최근 기록", ""]
    lines += [f"- {e.date} · {e.commit} · {e.summary}" for e in recent] or ["- 없음"]
    return "\n".join(lines) + "\n"


def render_status(repo: Path, config: dict) -> str:
    status_dir = (repo / config["status"]).parent
    lines = [
        GENERATED_MARK,
        "# Rosy OS module status",
        "",
        "각 모듈 `progress.md`의 gate 스냅샷을 모은 것이다. 계약은 SRS·API·ADR이 우선한다.",
        "",
        "| 모듈 | owner | last verified | " + " | ".join(GATES) + " |",
        "|---|---|---|" + "---|" * len(GATES),
    ]
    blockers: list[str] = []
    for module in config["modules"]:
        meta = _read_progress(repo, module)
        gates = meta.get("gates") or {}
        verified = meta.get("last_verified") or {}
        cells = [str((gates.get(g) or {}).get("state", "—")) for g in GATES]
        link = _link(status_dir, repo / module["path"] / "progress.md")
        lines.append(
            f"| [{module['name']}]({link}) | {meta.get('owner', '?')} | "
            f"{verified.get('commit', '?')} ({verified.get('date', '?')}) | " + " | ".join(cells) + " |"
        )
        for gate in GATES:
            if (gates.get(gate) or {}).get("state") == "HOLD":
                blockers.append(f"- {module['name']} {gate}: {gates[gate].get('blocker')}")
    lines += ["", "## HOLD blockers", ""] + (blockers or ["- 없음"])
    return "\n".join(lines) + "\n"


def render_brief(repo: Path) -> str:
    """Short session-start context: every module's gates and the record loop."""
    config = load_config(repo)
    lines = ["[Rosy OS module harness, ADR D-61] 모듈 gate (각 progress.md 기준, 계약은 SRS·API·ADR 우선):"]
    for module in config["modules"]:
        try:
            meta = _read_progress(repo, module)
        except HarnessError as exc:
            lines.append(f"- {module['name']}: {exc}")
            continue
        # One malformed record must not blank the brief; it is what the brief should show.
        problems = validate_progress(meta)
        if problems:
            lines.append(f"- {module['name']} ({module['path']}): invalid progress.md ({len(problems)} errors: {problems[0]})")
            continue
        gates = meta.get("gates") or {}
        cells = " ".join(f"{g}={(gates.get(g) or {}).get('state', '—')}" for g in GATES)
        commit = (meta.get("last_verified") or {}).get("commit", "?")
        lines.append(f"- {module['name']} ({module['path']}, verified {commit}): {cells}")
    lines += [
        "작업 순서: 모듈 progress.md·index.md 읽기 → 변경 → logs.md에 항목 추가 → gate가 바뀌면 progress.md 덮어쓰기"
        " → `python tools/harness/rosy_harness.py generate` → `lint`.",
        "HOLD blocker 전체: STATUS.md",
    ]
    return "\n".join(lines) + "\n"


def generated_targets(repo: Path) -> dict[Path, str]:
    config = load_config(repo)
    adr_path = repo / config["adr_log"]
    adr = parse_adr_log(adr_path.read_text(encoding="utf-8"))
    targets = {
        repo / m["path"] / "index.md": render_module_index(repo, m, adr, adr_path) for m in config["modules"]
    }
    targets[repo / config["status"]] = render_status(repo, config)
    return targets


def check_generated(repo: Path) -> list[str]:
    try:
        targets = generated_targets(repo)
    except (ValueError, OSError, yaml.YAMLError) as exc:
        return [f"cannot render: {exc}"]
    problems = []
    for path, content in targets.items():
        rel = path.relative_to(repo).as_posix()
        if not path.is_file():
            problems.append(f"{rel}: missing")
        elif _normalize(path.read_text(encoding="utf-8")) != content:
            problems.append(f"{rel}: stale")
    return problems


def generate(repo: Path) -> list[Path]:
    written = []
    for path, content in generated_targets(repo).items():
        if not path.is_file() or _normalize(path.read_text(encoding="utf-8")) != content:
            path.write_text(content, encoding="utf-8", newline="\n")
            written.append(path)
    return written


# --- lint ------------------------------------------------------------------


def _git(repo: Path, *args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args], capture_output=True, text=True, encoding="utf-8", check=False
        )
    except OSError:
        return None
    return result.stdout if result.returncode == 0 else None


def find_conflict_markers(text: str) -> list[int]:
    """1-based line numbers of git conflict markers at the start of a line."""
    return [number for number, line in enumerate(_normalize(text).split("\n"), start=1) if CONFLICT_MARKER.match(line)]


def _history_refs(repo: Path) -> tuple[list[str], str | None]:
    """Refs whose committed logs must survive: the CI base, the merge base, and HEAD.

    Comparing with HEAD alone only catches uncommitted edits; a rewritten entry
    that was already committed on the branch is caught against a base. A CI base
    that does not resolve (40 zeros on a new branch, an unfetched pre-force-push
    commit) widens to the merge base with a note instead of skipping silently.
    """
    note = None
    refs: list[str] = []
    # CI sends an empty string when neither a PR base nor a previous push exists.
    requested = os.environ.get("HARNESS_BASE_REF") or None
    if requested:
        resolvable = set(requested) != {"0"} and _git(repo, "rev-parse", "--verify", "--quiet", f"{requested}^{{commit}}")
        if resolvable:
            refs.append(requested)
        else:
            note = f"HARNESS_BASE_REF {requested[:12]} does not resolve; compared with the origin/main merge base"
    merge_base = _git(repo, "merge-base", "HEAD", "origin/main")
    if merge_base and merge_base.strip():
        refs.append(merge_base.strip())
    if not refs:
        missing = "append-only base unavailable (no origin/main or shallow clone); compared with HEAD only"
        note = f"{note}; {missing}" if note else missing
    return list(dict.fromkeys([*refs, "HEAD"])), note


def lint(repo: Path) -> tuple[list[str], list[str]]:
    config = load_config(repo)
    errors: list[str] = []
    warnings: list[str] = []

    adr_text = (repo / config["adr_log"]).read_text(encoding="utf-8")
    adr = parse_adr_log(adr_text)
    errors += [f"ADR log: {e}" for e in validate_adr_log(adr, config.get("adr_gaps") or {})]
    governed = [(config["adr_log"], adr_text)]
    for module in config["modules"]:
        for name in ("progress.md", "logs.md"):
            path = repo / module["path"] / name
            if path.is_file():
                governed.append((f"{module['path']}/{name}", path.read_text(encoding="utf-8")))
    for rel, text in governed:
        lines = find_conflict_markers(text)
        if lines:
            errors.append(f"{rel}: conflict marker at line {', '.join(map(str, lines))}")

    refs, note = _history_refs(repo)
    if note:
        warnings.append(note)

    for module in config["modules"]:
        name, base = module["name"], repo / module["path"]
        try:
            meta = _read_progress(repo, module)
        except HarnessError as exc:
            errors.append(str(exc))
            continue
        if meta.get("module") != name:
            errors.append(f"{name}/progress.md: module field is {meta.get('module')!r}")
        errors += [f"{name}/progress.md: {e}" for e in validate_progress(meta, known_adrs=set(adr.index))]
        errors += [f"{name}/progress.md: plan not found: {p}" for p in meta.get("plans") or [] if not (repo / p).is_file()]

        log_path = base / "logs.md"
        if not log_path.is_file():
            errors.append(f"{name}: missing logs.md")
        else:
            text = log_path.read_text(encoding="utf-8")
            errors += [f"{name}/logs.md: {e}" for e in validate_log(text)]
            for ref in refs:
                committed = _git(repo, "show", f"{ref}:{log_path.relative_to(repo).as_posix()}")
                if committed is not None and not is_append_only(committed, text):
                    errors.append(f"{name}/logs.md: entries committed at {ref[:12]} were edited; logs are append-only")

        commit = (meta.get("last_verified") or {}).get("commit")
        if commit == UNCOMMITTED:
            warnings.append(f"{name}: last_verified is an uncommitted tree; re-verify and record the commit")
        elif isinstance(commit, str):
            count = _git(repo, "rev-list", "--count", f"{commit}..HEAD", "--", module["path"])
            threshold = int(config.get("stale_after_commits", 5))
            if count is None:
                warnings.append(f"{name}: last_verified commit {commit} not found in git history")
            elif int(count) > threshold:
                warnings.append(f"{name}: {count.strip()} commits touched {module['path']} since last_verified {commit}")

    errors += [f"generated: {p}" for p in check_generated(repo)]
    return errors, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=("generate", "lint", "brief"))
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args(argv)
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    repo = args.repo.resolve()
    if args.command == "brief":
        print(render_brief(repo), end="")
        return 0
    if args.command == "generate":
        for path in generate(repo):
            print(f"wrote {path.relative_to(repo).as_posix()}")
        return 0

    errors, warnings = lint(repo)
    for warning in warnings:
        print(f"WARN  {warning}")
    for error in errors:
        print(f"ERROR {error}")
    print(f"{len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
