"""D-480 sim2real gap registry: validate rows and render the table.

Wired into ``rosy_harness.py lint`` / ``generate`` through ``harness.yaml`` keys
``sim2real_gaps`` and ``sim2real_table``. Tests: ``test/test_sim2real_gaps.py``.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ADR_ID = re.compile(r"^D-(\d+)$")
SIM2REAL_REQUIRED = ("id", "gap", "evidence", "tier", "owner", "status", "next")
SIM2REAL_TIERS = ("M", "R", "D", "infra")
SIM2REAL_STATUSES = ("OPEN", "IN-PROGRESS", "CLOSED", "HOLD")
GAP_ID = re.compile(r"^G-\d{2}$")
# A repo path with an optional line suffix: `a.py`, `a.py:33`, `a.py:26-33`, `a.py:33,108`.
EVIDENCE_PATH = re.compile(r"^(?P<path>[^:]+?)(?::(?P<lines>\d+(?:-\d+)?(?:,\d+(?:-\d+)?)*))?$")


def git(repo: Path, *args: str) -> str | None:
    try:
        result = subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True,
                                encoding="utf-8", check=False)
    except OSError:
        return None
    return result.stdout if result.returncode == 0 else None


def _cell(value) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _evidence_text(item) -> str:
    if isinstance(item, dict):
        return f"`{item.get('path')}` (branch {item.get('branch')})"
    return item if ADR_ID.match(str(item)) else f"`{item}`"


def render(registry: dict) -> str:
    lines = [
        "<!-- GENERATED by tools/harness/rosy_harness.py generate. "
        "Edit tools/harness/sim2real_gaps.yaml instead. -->",
        "# sim2real gap registry",
        "",
        "Tier: M 시뮬 모델링, R 실주행 재생, D 장치 런타임 지원, infra 실행 환경. "
        "첫 tier가 지금 자리이고 뒤 tier는 옮겨 갈 자리다. 규칙은 D-480 결정 7과 `rosy_harness.py lint`가 정한다.",
        "",
        "| id | gap | evidence | tier | owner | status | next |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in registry.get("gaps") or []:
        evidence = "<br>".join(_cell(_evidence_text(e)) for e in row.get("evidence") or [])
        status = row.get("status")
        if row.get("validated_by"):
            status = f"{status} ({_evidence_text(row['validated_by'])})"
        lines.append("| " + " | ".join([
            _cell(row.get("id")), _cell(row.get("gap")), evidence, "+".join(row.get("tier") or []),
            _cell(row.get("owner")), _cell(status), _cell(row.get("next")),
        ]) + " |")
    return "\n".join(lines) + "\n"


def _check_evidence(repo: Path, where: str, item, known_adrs: set[str]) -> tuple[list[str], list[str]]:
    """One evidence entry: an ADR id, a repo path (optional :lines), or {path, branch}."""
    if isinstance(item, dict):
        path, branch = item.get("path"), item.get("branch")
        if not isinstance(path, str) or not isinstance(branch, str):
            return [f"{where}: branch evidence needs string path and branch"], []
        for ref in (branch, f"origin/{branch}"):
            if git(repo, "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}"):
                if git(repo, "cat-file", "-e", f"{ref}:{path}") is None:
                    return [f"{where}: not found on {branch}: {path}"], []
                return [], []
        # Not an error: the branch landed (move the path) or this clone lacks it (CI).
        return [], [f"{where}: branch {branch} not available; {path} unchecked"]
    if not isinstance(item, str):
        return [f"{where}: evidence must be a string or {{path, branch}}"], []
    if ADR_ID.match(item):
        return ([] if item in known_adrs else [f"{where}: unknown ADR: {item}"]), []
    match = EVIDENCE_PATH.match(item)
    target = repo / match["path"] if match else None
    if target is None or not target.exists():
        return [f"{where}: not found: {match['path'] if match else item}"], []
    if match["lines"]:
        count = len(target.read_text(encoding="utf-8", errors="replace").splitlines())
        last = max(int(n) for n in re.split(r"[-,]", match["lines"]))
        if last > count:
            return [f"{where}: {match['path']} has {count} lines, cites line {last}"], []
    return [], []


def validate(registry: dict, repo: Path, known_adrs: set[str]) -> tuple[list[str], list[str]]:
    rows = (registry or {}).get("gaps")
    if not isinstance(rows, list):
        return ["gaps must be a list"], []
    errors: list[str] = []
    warnings: list[str] = []
    seen: set[str] = set()
    for number, row in enumerate(rows, start=1):
        if not isinstance(row, dict):
            errors.append(f"row {number}: must be a mapping")
            continue
        where = str(row.get("id", f"row {number}"))
        errors += [f"{where}: missing field: {key}" for key in SIM2REAL_REQUIRED if row.get(key) in (None, "", [])]
        gap_id = row.get("id")
        if gap_id is not None:
            if not isinstance(gap_id, str) or not GAP_ID.match(gap_id):
                errors.append(f"{where}: malformed id (want G-NN)")
            elif gap_id in seen:
                errors.append(f"{where}: duplicate id")
            seen.add(gap_id)
        tier = row.get("tier")
        if tier is not None and (not isinstance(tier, list) or not tier or len(set(tier)) != len(tier)
                                 or any(t not in SIM2REAL_TIERS for t in tier)):
            errors.append(f"{where}: tier must be a non-empty list of distinct {'/'.join(SIM2REAL_TIERS)}")
        if row.get("status") is not None and row["status"] not in SIM2REAL_STATUSES:
            errors.append(f"{where}: unknown status {row['status']!r}")
        evidence = row.get("evidence")
        if evidence is not None and not isinstance(evidence, list):
            errors.append(f"{where}: evidence must be a list")
            evidence = []
        checks = [(f"{where} evidence", item) for item in evidence or []]
        if row.get("status") == "CLOSED":
            if not row.get("validated_by"):
                errors.append(f"{where}: CLOSED requires validated_by")
            else:
                checks.append((f"{where} validated_by", row["validated_by"]))
        for label, item in checks:
            item_errors, item_warnings = _check_evidence(repo, label, item, known_adrs)
            errors += item_errors
            warnings += item_warnings
    return errors, warnings
