"""MAP v2 fleet — 260919 STL becomes a Gazebo road scene without reshaping it."""

import importlib.util
import struct
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "map" / "map_v2_fleet"
SOURCE = BUNDLE / "260919 MAP FILE.STL"
WORLD = BUNDLE / "worlds" / "map_v2_fleet.world"
MESH = BUNDLE / "meshes" / "road_lines.stl"
MAP_YAML = BUNDLE / "maps" / "map_v2_fleet.yaml"


def _load(name):
    spec = importlib.util.spec_from_file_location(name, BUNDLE / "scripts" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def scene():
    return _load("stl_scene").load_scene(SOURCE)


def test_source_is_the_reviewed_binary_stl(scene):
    assert scene.triangle_count == 1768
    assert len(scene.source_sha256) == 64


def test_footprint_is_centred_in_metres(scene):
    assert scene.size_x == pytest.approx(2.810, abs=1e-4)
    assert scene.size_y == pytest.approx(1.260, abs=1e-4)
    xs = [v[0] for t in scene.lines for v in t]
    ys = [v[1] for t in scene.lines for v in t]
    assert min(xs) >= -1.4051 and max(xs) <= 1.4051
    assert min(ys) >= -0.6301 and max(ys) <= 0.6301


def test_perimeter_ring_becomes_four_wall_boxes(scene):
    walls = scene.walls
    assert len(walls) == 4
    for wall in walls:
        assert min(wall.size_x, wall.size_y) == pytest.approx(0.005, abs=1e-6)
        assert wall.height == pytest.approx(0.155, abs=1e-6)
    long_walls = sorted(max(w.size_x, w.size_y) for w in walls)
    assert long_walls[-1] == pytest.approx(2.810, abs=1e-4)


def test_floor_paint_is_flat_and_below_one_millimetre(scene):
    assert len(scene.lines) == 1768 - scene.wall_triangle_count
    assert max(v[2] for t in scene.lines for v in t) <= 0.001


def test_rotation_is_proper_not_mirrored():
    mod = _load("stl_scene")
    # STL Y-up: +z (toward viewer) must map to ROS -y; +y (up) to ROS +z.
    assert mod.stl_to_ros((0.0, 0.0, 1000.0), (0.0, 0.0)) == pytest.approx((0.0, -1.0, 0.0))
    assert mod.stl_to_ros((0.0, 1000.0, 0.0), (0.0, 0.0)) == pytest.approx((0.0, 0.0, 1.0))


def test_rejects_truncated_stl(tmp_path):
    bad = tmp_path / "bad.stl"
    bad.write_bytes(b"\0" * 80 + struct.pack("<I", 5))
    with pytest.raises(ValueError, match="binary STL"):
        _load("stl_scene").load_scene(bad)


def test_builder_output_is_deterministic_and_checked_in(tmp_path):
    build = _load("build_world")
    build.build(SOURCE, tmp_path)
    assert (tmp_path / "worlds" / "map_v2_fleet.world").read_bytes() == WORLD.read_bytes()
    assert (tmp_path / "meshes" / "road_lines.stl").read_bytes() == MESH.read_bytes()


def test_world_has_four_lidar_height_wall_collisions_only():
    world = ET.parse(WORLD).getroot().find("world")
    boxes = [c for c in world.iter("collision") if c.find("./geometry/box") is not None]
    assert len(boxes) == 4
    assert not [c for c in world.iter("collision") if c.find("./geometry/mesh") is not None]


def test_lane_mesh_is_visual_only_above_the_ground_plane():
    world = ET.parse(WORLD).getroot().find("world")
    uris = [u.text for u in world.iter("uri")]
    assert "model://control/map/map_v2_fleet/meshes/road_lines.stl" in uris
    lines = world.find("./model[@name='road_lines']")
    assert lines.find("static").text == "true"
    assert float(lines.find("pose").text.split()[2]) == pytest.approx(0.001)


def test_world_records_the_source_hash(scene):
    assert scene.source_sha256 in WORLD.read_text(encoding="utf-8")


def test_white_lines_on_dark_floor_by_default():
    """The physical 260919 mat is white tape on a dark floor (lane.py polarity)."""
    text = WORLD.read_text(encoding="utf-8")
    assert "<diffuse>0.2 0.2 0.2 1</diffuse>" in text  # floor
    assert "<diffuse>1 1 1 1</diffuse>" in text        # lane paint


def test_occupancy_map_matches_the_wall_ring():
    meta = yaml.safe_load(MAP_YAML.read_text(encoding="utf-8"))
    assert meta["image"] == "map_v2_fleet.pgm"
    assert meta["resolution"] == pytest.approx(0.01)
    pgm = (BUNDLE / "maps" / meta["image"]).read_bytes()
    assert pgm.startswith(b"P5")
    # world_to_map.py writes "P5\n# generated by world_to_map.py\n<w> <h>\n255\n" —
    # line 1 is the comment, so the width/height pair is line index 2, not 1.
    width, height = (int(v) for v in pgm.split(b"\n")[2].split())
    # 2.81 x 1.26 m ring + 0.3 m margin on each side, 1 cm cells.
    assert width == pytest.approx(341, abs=2)
    assert height == pytest.approx(186, abs=2)
