#!/usr/bin/env python3
"""Build worlds/map_v2_fleet.world and meshes/road_lines.stl from the 260919 STL.

Usage: python build_world.py [--out BUNDLE_DIR] [--line-colour bright|dark]
Output is byte-deterministic; re-run and diff before committing.
"""

import argparse
import importlib.util
import struct
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUNDLE = HERE.parent
SOURCE = BUNDLE / "260919 MAP FILE.STL"
MESH_URI = "model://control/map/map_v2_fleet/meshes/road_lines.stl"
COLOURS = {
    # (floor, paint): dark = black tape on white mat, bright = white tape on dark floor
    "dark": ("1 1 1 1", "0.05 0.05 0.05 1"),
    "bright": ("0.2 0.2 0.2 1", "1 1 1 1"),
}


def _scene_module():
    spec = importlib.util.spec_from_file_location("stl_scene", HERE / "stl_scene.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _normal(t):
    (ax, ay, az), (bx, by, bz), (cx, cy, cz) = t
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    length = (nx * nx + ny * ny + nz * nz) ** 0.5 or 1.0
    return nx / length, ny / length, nz / length


def write_mesh(lines, path: Path) -> None:
    header = b"rosy map_v2_fleet road_lines (metres, Z-up)".ljust(80, b" ")
    body = bytearray(header + struct.pack("<I", len(lines)))
    for t in lines:
        body += struct.pack("<12fH", *_normal(t), *t[0], *t[1], *t[2], 0)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(body))


def _wall_xml(i: int, w) -> str:
    pose = f"{w.cx:.5f} {w.cy:.5f} {w.height / 2:.5f} 0 0 0"
    size = f"{w.size_x:.5f} {w.size_y:.5f} {w.height:.5f}"
    return f"""        <collision name="wall_{i:02d}_col">
          <pose>{pose}</pose>
          <geometry><box><size>{size}</size></box></geometry>
          <surface><friction><ode><mu>0.9</mu><mu2>0.9</mu2></ode></friction></surface>
        </collision>
        <visual name="wall_{i:02d}_vis">
          <pose>{pose}</pose>
          <geometry><box><size>{size}</size></box></geometry>
          <material><ambient>0.30 0.35 0.45 1</ambient><diffuse>0.30 0.35 0.45 1</diffuse></material>
        </visual>
"""


def world_xml(scene, line_colour: str) -> str:
    floor, paint = COLOURS[line_colour]
    walls = "".join(_wall_xml(i, w) for i, w in enumerate(scene.walls))
    return f"""<?xml version="1.0"?>
<!-- MAP v2 fleet / 260919 — generated by scripts/build_world.py. Do not edit.
  Source: 260919 MAP FILE.STL sha256 {scene.source_sha256}
  Envelope {scene.size_x:.3f} x {scene.size_y:.3f} m, centred at the origin.
  STL Y-up mm -> ROS Z-up m by R_x(+90 deg); no reshaping.
  Lane paint is visual-only; the perimeter ring is the only collision.
  Line colour: {line_colour}. Orientation vs the physical mat: see README.md.
-->
<sdf version="1.6">
  <world name="map_v2_fleet">
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics">
      <engine><filename>gz-physics-dartsim-plugin</filename></engine>
    </plugin>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>

    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.4 0.2 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <material><ambient>{floor}</ambient><diffuse>{floor}</diffuse></material>
        </visual>
      </link>
    </model>

    <model name="road_lines">
      <static>true</static>
      <pose>0 0 0.001 0 0 0</pose>
      <link name="link">
        <visual name="paint">
          <geometry><mesh><uri>{MESH_URI}</uri></mesh></geometry>
          <material><ambient>{paint}</ambient><diffuse>{paint}</diffuse></material>
        </visual>
      </link>
    </model>

    <model name="track_v2_fleet">
      <static>true</static>
      <pose>0 0 0 0 0 0</pose>
      <link name="link">
{walls}      </link>
    </model>
  </world>
</sdf>
"""


def build(source: Path, out: Path, line_colour: str = "bright") -> None:
    scene = _scene_module().load_scene(source)
    write_mesh(scene.lines, out / "meshes" / "road_lines.stl")
    world = out / "worlds" / "map_v2_fleet.world"
    world.parent.mkdir(parents=True, exist_ok=True)
    world.write_text(world_xml(scene, line_colour), encoding="utf-8", newline="\n")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, default=BUNDLE)
    p.add_argument("--line-colour", choices=sorted(COLOURS), default="bright")
    args = p.parse_args(argv)
    build(SOURCE, args.out, args.line_colour)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
